### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by ritik-kansal** [kyokenn/rogdrv#13]
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

**Comment by kyokenn** [comment]
Which python-hid package you have installed? Do you have libhidapi installed?
