### ISSUE TITLE
Lenovo Legion M600 Wireless Gaming Mouse - doesn't work in Bluetooth mode

### ISSUE THREAD

**Issue by bam80** [kyokenn/rogdrv#35]
Hi, many thanks for this project!

My question might be out of scope here still I hope for your help.
Just bought [mentioned mouse](https://www.lenovo.com/us/en/p/accessories-and-software/keyboards-and-mice/mice/GY50X79385), it works fine on Linux in USB cable and wireless adapter modes but in Bluetooth mode doesn't show any evidence of life after being successfully paired and connected.
`btmon` shows events, though - here is the dump in binary and text formats:
https://www.spinics.net/lists/linux-bluetooth/msg96904.html

Important note the mouse works fine with BT on my ancient tablet with Android 8.10. This mouse didn't even exist when it stopped updating..

Could you help me to understand what's wrong with this mouse on Linux?
I need to make a decision if I return it to store or keep it in hope it will be fixed soon..

**Comment by kyokenn** [comment]
Some mice requires a specific version of BT, some of them requires BT LE. Make sure to check the mouse and BT adapter specs. You can also boot into Windows VM and pass BT adapter into VM.

**Comment by bam80** [comment]
I have Windows 10 as a second system installed on the same PC. The mouse works there via BT out of the box, even before any additional Lenovo software installed.
Also, as seen in the logs above - in Linux it pairs and connects, and even events can be seen with `btmon`. It just doesn't work in BT mode, but works in RF an USB cable modes.

So I wonder does it use some custom HID protocol via BT, or the protocol is standard and the problem in something else, considering it also works on Android via BT?

PS:
yes the mouse connects BT 5.0 or BLE, but I have corresponded BT adapter, so problem is not there (as I said it connects actually).

**Comment by bam80** [comment]
It's upstream problem with linux BT/HID stack, see the link above.
