### ISSUE TITLE
"/dev/uinput" cannot be opened for writing and proposed solution

### ISSUE THREAD

**Issue by xBazilio** [kyokenn/rogdrv#5]
```
$ rogdrv
Traceback (most recent call last):
  File "/usr/local/bin/rogdrv", line 11, in <module>
    load_entry_point('rogdrv==0.0.5', 'console_scripts', 'rogdrv')()
  File "/usr/local/lib/python3.7/dist-packages/rogdrv-0.0.5-py3.7.egg/rogdrv/__main__.py", line 42, in rogdrv
    handler = EventHandler()
  File "/usr/local/lib/python3.7/dist-packages/rogdrv-0.0.5-py3.7.egg/rogdrv/device.py", line 32, in __init__
    self._uinput = uinput.UInput()
  File "/usr/lib/python3/dist-packages/evdev/uinput.py", line 124, in __init__
    self._verify()
  File "/usr/lib/python3/dist-packages/evdev/uinput.py", line 262, in _verify
    raise UInputError(msg.format(self.devnode))
evdev.uinput.UInputError: "/dev/uinput" cannot be opened for writing
```
Adding `KERNEL=="uinput", MODE="0666"` to the top of `/etc/udev/rules.d/50-rogdrv.rules` and reloading rules solves the problem

**Comment by xBazilio** [comment]
```
$ lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0b05:1816 ASUSTek Computer, Inc. 
Bus 001 Device 003: ID 04d9:1702 Holtek Semiconductor, Inc. Keyboard LKS02
```
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
```

Buzzard mouse

**Comment by kyokenn** [comment]
This is a strange error. I didn't had it on Ubuntu 19.04.
It's related to the uinput virtual device subsystem, which I'm using as a virtual keyboard for sending the keyboard events.
Somehow I'm getting added as user to the /dev/uinput file's ACL. Maybe it's something related to the gnome-shell session.

> Adding KERNEL=="uinput", MODE="0666" to the top of /etc/udev/rules.d/50-rogdrv.rules and reloading rules solves the problem

Maybe it's not the best solution, but I don't have a better one atm. So I have added it to the .rules file. - 

Thanks for the report!
