### ISSUE TITLE
Asus rog gladius 2 wireless support

### ISSUE THREAD

**Issue by kvvvseins** [kyokenn/rogdrv#60]
Hello, could you plz add support that Asus rog gladius 2 wireless?

**Comment by kyokenn** [comment]
What usb ID does it have? You can check it with `lsusb`

**Comment by LisciOusko** [comment]
Hi, having the same issue with my ROG Gladius II Wireless. The ID in USB mode is 0x189e. In RF mode, it is 0x18a0.

**Comment by kyokenn** [comment]
I have added it to the ratbag-python. You can test, if it works for you.

**Comment by LisciOusko** [comment]
Works just fine now! Thank you so much, this project is a real lifesaver.
