### ISSUE TITLE
Doesn't work with all ROG Gladius II mice

### ISSUE THREAD

**Issue by ghost** [kyokenn/rogdrv#7]
The README lists the Gladius II as a supported mouse.  My Gladius II has a different ID than the one in the source: 0b05:1845 (it shows up as a USB2.0 hub).  I replaced the ID in the source and after playing with the rogdrv-config command, found that I was able to change some colors.  However it took some experimentation to get the mouse out of the default (rainbow) mode.  I suggest you add this USB ID to the source for others.

**Comment by kyokenn** [comment]
Ok. I have added it. Thanks.
